import { supabase } from './supabase';

export type FoodRelation = 'before' | 'after' | 'any';
export type DurationType = 'ongoing' | 'course';
export type DoseStatus = 'pending' | 'taken' | 'missed';

export interface Medicine {
  id: string;
  owner_id: string;
  is_managed_profile: boolean;
  name: string;
  dosage: string;
  frequency: string;
  times: string[];
  food_relation: FoodRelation;
  duration_type: DurationType;
  duration_end_date: string | null;
  active: boolean;
}

export interface DoseLogEntry {
  id: string;
  medicine_id: string;
  owner_id: string;
  scheduled_for: string; // ISO timestamp
  status: DoseStatus;
  taken_at: string | null;
  medicines?: { name: string; dosage: string; food_relation: FoodRelation };
}

export interface NewMedicineInput {
  name: string;
  dosage: string;
  frequency: string;
  times: string[];
  foodRelation: FoodRelation;
  durationType: DurationType;
  durationEndDate?: string;
}

// Creates the medicine row, then immediately generates today's dose_log
// entries for it (any times still in the future today). Future days' doses
// are generated by a daily job later — see Phase E for the scheduled
// Edge Function version; for now, generateTodaysDoseLogs() covers a single
// day and can be re-run each app open to backfill today if needed.
export async function addMedicine(input: NewMedicineInput): Promise<Medicine> {
  const { data: sessionData } = await supabase.auth.getSession();
  const userId = sessionData.session?.user.id;
  if (!userId) throw new Error('No active session');

  const { data, error } = await supabase
    .from('medicines')
    .insert({
      owner_id: userId,
      is_managed_profile: false,
      name: input.name,
      dosage: input.dosage,
      frequency: input.frequency,
      times: input.times,
      food_relation: input.foodRelation,
      duration_type: input.durationType,
      duration_end_date: input.durationEndDate ?? null,
      active: true,
    })
    .select()
    .single();

  if (error) throw error;

  await generateDoseLogsForMedicine(data as Medicine);

  return data as Medicine;
}

// Generates dose_log rows for today for a single medicine. Safe to call
// multiple times — checks for existing entries at the same scheduled time
// before inserting, to avoid duplicates.
export async function generateDoseLogsForMedicine(medicine: Medicine) {
  const today = new Date();
  const todayStr = today.toISOString().slice(0, 10);

  const { data: existing } = await supabase
    .from('dose_log')
    .select('scheduled_for')
    .eq('medicine_id', medicine.id)
    .gte('scheduled_for', `${todayStr}T00:00:00`)
    .lte('scheduled_for', `${todayStr}T23:59:59`);

  const existingTimes = new Set((existing ?? []).map((e) => e.scheduled_for));

  const rowsToInsert = medicine.times
    .map((time) => {
      const [hours, minutes] = time.split(':').map(Number);
      const scheduledFor = new Date(today);
      scheduledFor.setHours(hours, minutes, 0, 0);
      return scheduledFor.toISOString();
    })
    .filter((iso) => !existingTimes.has(iso))
    .map((scheduledFor) => ({
      medicine_id: medicine.id,
      owner_id: medicine.owner_id,
      scheduled_for: scheduledFor,
      status: 'pending' as DoseStatus,
    }));

  if (rowsToInsert.length === 0) return;

  const { error } = await supabase.from('dose_log').insert(rowsToInsert);
  if (error) throw error;
}

export async function getTodaysDoses(): Promise<DoseLogEntry[]> {
  const { data: sessionData } = await supabase.auth.getSession();
  const userId = sessionData.session?.user.id;
  if (!userId) throw new Error('No active session');

  const todayStr = new Date().toISOString().slice(0, 10);

  const { data, error } = await supabase
    .from('dose_log')
    .select('*, medicines(name, dosage, food_relation)')
    .eq('owner_id', userId)
    .gte('scheduled_for', `${todayStr}T00:00:00`)
    .lte('scheduled_for', `${todayStr}T23:59:59`)
    .order('scheduled_for', { ascending: true });

  if (error) throw error;
  return data as DoseLogEntry[];
}

export async function getAllMedicines(): Promise<Medicine[]> {
  const { data: sessionData } = await supabase.auth.getSession();
  const userId = sessionData.session?.user.id;
  if (!userId) throw new Error('No active session');

  const { data, error } = await supabase
    .from('medicines')
    .select('*')
    .eq('owner_id', userId)
    .order('active', { ascending: false });

  if (error) throw error;
  return data as Medicine[];
}

export async function updateMedicine(
  medicineId: string,
  input: NewMedicineInput,
): Promise<Medicine> {
  const { data, error } = await supabase
    .from('medicines')
    .update({
      name: input.name,
      dosage: input.dosage,
      frequency: input.frequency,
      times: input.times,
      food_relation: input.foodRelation,
      duration_type: input.durationType,
      duration_end_date: input.durationEndDate ?? null,
    })
    .eq('id', medicineId)
    .select()
    .single();

  if (error) throw error;

  // Clear today's still-pending doses for this medicine and regenerate —
  // simplest way to reflect a changed time/frequency without manual diffing.
  // Doses already taken or missed are left untouched (real history).
  await supabase
    .from('dose_log')
    .delete()
    .eq('medicine_id', medicineId)
    .eq('status', 'pending');

  await generateDoseLogsForMedicine(data as Medicine);

  return data as Medicine;
}

export async function deleteMedicine(medicineId: string) {
  // dose_log rows cascade-delete via the FK's "on delete cascade" — see schema.
  const { error } = await supabase
    .from('medicines')
    .delete()
    .eq('id', medicineId);
  if (error) throw error;
}

export async function getMedicineById(medicineId: string): Promise<Medicine> {
  const { data, error } = await supabase
    .from('medicines')
    .select('*')
    .eq('id', medicineId)
    .single();

  if (error) throw error;
  return data as Medicine;
}

export async function markMedicineInactive(medicineId: string) {
  const { error } = await supabase
    .from('medicines')
    .update({ active: false })
    .eq('id', medicineId);
  if (error) throw error;
}

export async function markDoseTaken(doseLogId: string) {
  const { error } = await supabase
    .from('dose_log')
    .update({ status: 'taken', taken_at: new Date().toISOString() })
    .eq('id', doseLogId);

  if (error) throw error;
}
